import { siteConfig } from "@/lib/config";
import { formatLongDate } from "@/lib/date";

export interface PassCardProps {
  name: string;
  passId: string;
  qrSvg: string;
  phoneMasked: string;
  issuedDate: string;
  /** "new" for a first registration, "welcome" for a returning visitor. */
  variant: "new" | "welcome";
  totalVisits: number;
  mismatch?: boolean;
  /** Rendered only outside print. */
  children?: React.ReactNode;
}

/**
 * The pass itself. Deliberately shows no date of birth and only a masked
 * phone number, so the printable page at /pass/[passId] leaks very little if
 * the link is ever shared.
 */
export function PassCard({
  name,
  passId,
  qrSvg,
  phoneMasked,
  issuedDate,
  variant,
  totalVisits,
  mismatch = false,
  children,
}: PassCardProps) {
  const readable = passId.match(/.{1,4}/g)?.join(" ") ?? passId;

  return (
    <div className="overflow-hidden rounded-2xl border-2 border-saffron-300 bg-white shadow-lg shadow-saffron-900/10">
      <div className="flex items-center justify-between gap-3 bg-saffron-500 px-5 py-3 text-white">
        <p className="text-sm font-semibold tracking-wide uppercase">
          {siteConfig.name}
        </p>
        <p className="text-xs font-medium opacity-90">{siteConfig.centreName}</p>
      </div>

      <div className="flex flex-col items-center gap-5 px-6 py-7 sm:flex-row sm:items-start">
        <div className="shrink-0 rounded-xl border border-saffron-200 bg-white p-2">
          {/* Generated by the local qrcode library from our own pass URL. */}
          <div
            className="h-[168px] w-[168px] [&>svg]:h-full [&>svg]:w-full"
            dangerouslySetInnerHTML={{ __html: qrSvg }}
          />
        </div>

        <div className="min-w-0 flex-1 text-center sm:text-left">
          <p className="text-xs font-semibold tracking-widest text-saffron-700 uppercase">
            {variant === "new" ? "Pass issued" : "Welcome back"}
          </p>
          <h2 className="mt-1 text-2xl leading-tight font-bold break-words text-ink-900">
            {name}
          </h2>

          <dl className="mt-4 space-y-1.5 text-sm">
            <div className="flex justify-between gap-3 sm:justify-start">
              <dt className="text-ink-500">Pass ID</dt>
              <dd className="font-mono font-semibold tracking-wider text-ink-900">
                {readable}
              </dd>
            </div>
            <div className="flex justify-between gap-3 sm:justify-start">
              <dt className="text-ink-500">Phone</dt>
              <dd className="text-ink-900">{phoneMasked}</dd>
            </div>
            <div className="flex justify-between gap-3 sm:justify-start">
              <dt className="text-ink-500">Date</dt>
              <dd className="text-ink-900">{formatLongDate(issuedDate)}</dd>
            </div>
            {totalVisits > 1 && (
              <div className="flex justify-between gap-3 sm:justify-start">
                <dt className="text-ink-500">Attendances</dt>
                <dd className="text-ink-900">{totalVisits}</dd>
              </div>
            )}
          </dl>
        </div>
      </div>

      <div className="border-t border-saffron-100 bg-saffron-50 px-5 py-3 text-center text-xs text-ink-700">
        Show this pass at the entrance on every Sunday. Screenshot it or keep
        this page open.
      </div>

      {mismatch && (
        <p className="border-t border-saffron-200 bg-saffron-100 px-5 py-3 text-center text-xs text-ink-700">
          You told us you had attended before, but this is a new record. Please
          mention it to a volunteer so we can merge it.
        </p>
      )}

      {children && (
        <div className="border-t border-saffron-100 px-5 py-3 print:hidden">{children}</div>
      )}
    </div>
  );
}
