import QRCode from "qrcode";

/**
 * Renders a QR code as an inline SVG string. Generated by a local library from
 * our own pass URL, so the output contains no interpolated user text and is
 * safe to inject.
 */
export async function qrSvg(data: string): Promise<string> {
  return QRCode.toString(data, {
    type: "svg",
    errorCorrectionLevel: "M",
    margin: 1,
    width: 260,
    color: { dark: "#1c1917ff", light: "#ffffffff" },
  });
}
